### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by deywang** [f5devcentral/f5-telemetry-analytics#33]
[root@localhost scripts]# ./start-all.sh 
vm.max_map_count = 262144
ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "/root/f5-telemetry-analytics/scripts/../deps/conf.d/docker-compose.yml", line 56, column 4

**Comment by deywang** [comment]
[root@localhost scripts]# ./start-all.sh 
vm.max_map_count = 262144
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '/root/f5-telemetry-analytics/scripts/../deps/conf.d/docker-compose.yml'

**Comment by zongzw** [comment]
我刚更新了README.md， 能否再尝试下。 

在跑start_all.sh 之前需要用 ansible脚本去生成相关的运行配置。

这样做的目的是 支持两种不同的运行模式，full 和 concise， concise可能是您需要的模式，它仅启动必要的container（Elasticsearch Logstash Kibana），并做必要的配置。

有问题再聊。 @deywang

**Comment by deywang** [comment]
root@rancher-n2:~/f5-telemetry-analytics# ansible-playbook -i conf.d/env.ini -e@conf.d/configs.yml auto/build-docker-images.yml

PLAY [hostnames] ************************************************************************************************************************************

TASK [rebuild docker images] ************************************************************************************************************************





changed: [10.145.74.87 -> localhost] => (item=ctrlbox)
changed: [10.145.74.87 -> localhost] => (item=fluentd)

PLAY RECAP ******************************************************************************************************************************************
10.145.74.87               : ok=1    changed=1    unreachable=0    failed=0   

root@rancher-n2:~/f5-telemetry-analytics# 
root@rancher-n2:~/f5-telemetry-analytics# 
root@rancher-n2:~/f5-telemetry-analytics# 
root@rancher-n2:~/f5-telemetry-analytics# 
root@rancher-n2:~/f5-telemetry-analytics# 
root@rancher-n2:~/f5-telemetry-analytics# cd scripts/
root@rancher-n2:~/f5-telemetry-analytics/scripts# ./start-all.sh 
vm.max_map_count = 262144
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '/root/f5-telemetry-analytics/scripts/../deps/conf.d/docker-compose.yml'
root@rancher-n2:~/f5-telemetry-analytics/scripts#

**Comment by deywang** [comment]
root@rancher-n2:~/f5-telemetry-analytics# tree deps/
deps/
└── conf.d
    ├── elasticsearch
    ├── fluentd
    │   └── ASM_conf
    ├── kibana-exports
    ├── logstash
    │   ├── index-lifecycle
    │   ├── index-templates
    │   └── pipelines
    │       ├── general
    │       ├── json
    │       └── regex
    └── nginx-dashboards

13 directories, 0 files

**Comment by deywang** [comment]
root@rancher-n2:~/f5-telemetry-analytics# !48
ansible-playbook -i conf.d/env.ini -e@conf.d/configs.yml auto/build-docker-images.yml

PLAY [hostnames] *************************************************************************************************************************************************************************

TASK [rebuild docker images] *************************************************************************************************************************************************************
changed: [10.145.74.87 -> localhost] => (item=ctrlbox)
changed: [10.145.74.87 -> localhost] => (item=fluentd)

PLAY RECAP *******************************************************************************************************************************************************************************
10.145.74.87               : ok=1    changed=1    unreachable=0    failed=0   

root@rancher-n2:~/f5-telemetry-analytics# !52
ansible-playbook -i conf.d/env.ini -e@conf.d/configs.yml auto/generate-runtime-configs.yml

PLAY [hostnames] *************************************************************************************************************************************************************************

TASK [copy conf.d to deps] ***************************************************************************************************************************************************************
changed: [10.145.74.87 -> localhost]

TASK [find all .j2 files] ****************************************************************************************************************************************************************
ok: [10.145.74.87 -> localhost]

TASK [generate configurations from .j2] **************************************************************************************************************************************************
changed: [10.145.74.87 -> localhost] => (item=../deps/conf.d/docker-compose.yml.j2)
changed: [10.145.74.87 -> localhost] => (item=../deps/conf.d/logstash/index-templates/general-template.tmpl.j2)
changed: [10.145.74.87 -> localhost] => (item=../deps/conf.d/logstash/index-lifecycle/general-ilm.j2)
changed: [10.145.74.87 -> localhost] => (item=../deps/conf.d/logstash/pipelines/general/general.conf.j2)

TASK [delete .j2 file] *******************************************************************************************************************************************************************
changed: [10.145.74.87 -> localhost] => (item=../deps/conf.d/docker-compose.yml.j2)
changed: [10.145.74.87 -> localhost] => (item=../deps/conf.d/logstash/index-templates/general-template.tmpl.j2)
changed: [10.145.74.87 -> localhost] => (item=../deps/conf.d/logstash/index-lifecycle/general-ilm.j2)
changed: [10.145.74.87 -> localhost] => (item=../deps/conf.d/logstash/pipelines/general/general.conf.j2)

PLAY RECAP *******************************************************************************************************************************************************************************
10.145.74.87               : ok=4    changed=3    unreachable=0    failed=0   

root@rancher-n2:~/f5-telemetry-analytics# ls
auto  conf.d  data  deps  docker  docs  logs  README.md  requirements.txt  scripts  test
root@rancher-n2:~/f5-telemetry-analytics# ./scripts/start-all.sh 
vm.max_map_count = 262144
Creating network "confd_ta-net" with the default driver
Pulling elasticsearch (elasticsearch:7.14.2)...
7.14.2: Pulling from library/elasticsearch
7.14.2: Pulling from library/elasticsearch
7a0437f04f83: Pull complete
600da26e6cb4: Extracting [==================================================>]  91.79MB/91.79MB
7b994055406c: Download complete

**Comment by deywang** [comment]
可以了，谢谢
